default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: railsdev
  password: railsdev


development:
  <<: *default
  database: local_jobs_dev

test:
  <<: *default
  database: local_jobs_test