# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ee10cc35e642105d575b71da3f62839b88712fabe4b5e9cd74159b91b44f89f6792f324a1c2af6d18a888296678ac00e1967a6f6439f9208bf7307dc7dd9064

test:
  secret_key_base: e2c558a69156a406af1d2bc99ff5c207810ee212e574f7eeff5bb25435f4cca4035169a244007133908e69c078fa3792605d66e7775a9ba99cdf4647ad52358d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
